### ISSUE TITLE
Changes to Interact with new Reactive

### ISSUE THREAD

**Issue by jverzani** [JuliaLang/Interact.jl#88]
Hi @shashi . I was using the pattern presented [here](https://groups.google.com/forum/?fromgroups#!topic/julia-users/Ur5b2_dsJyA) to update a plot when a button is pressed, and not when each control is manipulated. I find a few things I don't know how to circumvent.

1. In the call `lift(tuple, α, β, γ)` there is an error even after changing `lift` to `map`. I think this is because the widgets no longer inherit from `Node`. 

2. Working around this with `vals = map(tuple, α.signal, β.signal, γ.signal)` I can then try to call `sampleon`: `coeffs = sampleon(replot, vals)`. But this gives an error: `LoadError: type Button has no field actions`. Likely this is due to the button not being of Node type.

I'm not sure what should be done here. Is there an alternative pattern I should be using?

**Comment by shashi** [comment]
The old Reactive + Interact had a way of directly "substituting" signals of the widgets when used with Reactive functions like lift and sampleon. This has been removed. So now you will need to use

`map(tuple, signal(α), signal(β), signal(γ))` and so on....

if α, β, γ are widgets.

Part of the reason is because `Base.map` cannot be made generic like that.

**Comment by jverzani** [comment]
What about the usage of `sampleon` Is there a workaround for that?

**Comment by shashi** [comment]
I suppose `replot` is a button. `coeffs = sampleon(signal(replot), vals)` should work.

**Comment by jverzani** [comment]
Thanks! That does work just as a I want.
