### ISSUE TITLE
Javascript error adding output! TypeError: require is not a function

### ISSUE THREAD

**Issue by diegozea** [JuliaLang/Interact.jl#92]
I found this error.
Here I'm working in the `dev` version of `Plots`. I used `plotly()` before in that notebook.
Same issue: https://github.com/tbreloff/Plots.jl/issues/164

![image](https://cloud.githubusercontent.com/assets/2822757/13761958/b2104444-ea1a-11e5-9d6d-dc5b29042693.png)

Best,

**Comment by spencerlyon2** [comment]
This is an issue with how I was loading Plotly (I made `require`, `requirejs`, and `define` undefined).

I've fixed this here: https://github.com/spencerlyon2/PlotlyJS.jl/commit/8b4a9e208d48287c9505490a9f128e419da4705e

It should be implemented in Plots.jl soon (whenever @tbreloff gets to it).

This issue should be closed.

**Comment by tbreloff** [comment]
Was there a reason you had that? Can I remove without consequence?

**Comment by spencerlyon2** [comment]
I had it has a hack that let us sidestep the require.js system to load plotly. It worked for what I needed, so I kept doing it.

Now it is causing problems so instead of sidestepping it, we leverage it. You should definitely use the new snippet from that commit instead of the currently borrowed one you use [here](https://github.com/tbreloff/Plots.jl/blob/8b2a83838894dc6d7f903a75e209362137e4d237/src/backends/plotly.jl#L9-L28)

**Comment by tbreloff** [comment]
Ok great. Thanks for lending it ;)

**Comment by shashi** [comment]
@diegozea so is this an Interact issue? or is it plotly? let me know if this can be closed

**Comment by spencerlyon2** [comment]
It can be closed. 

This is an issue with how plotly.js is being loaded

**Comment by shashi** [comment]
thanks!
